# Generated by Django 3.1.6 on 2021-03-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210316_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('jobKind', models.CharField(choices=[('Svarchik', 'Svarchik'), ('Payvandchi', 'Payvandchi'), ('Kaflechi', 'Kaflechi'), ('Boshqa Kasb', 'Boshqa Kasb')], default='Boshqa Kasb', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
