# Generated by Django 3.1.6 on 2021-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_contacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contacted',
        ),
        migrations.AddField(
            model_name='message',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='jobType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='jobKind',
            field=models.CharField(choices=[('Сантехника', 'Сантехника'), ('Электроэнергия', 'Электроэнергия'), ('Связь', 'Связь'), ('Интернетb', 'Интернет'), ('Бытовая техника (ремонт)', 'Бытовая техника (ремонт)'), ('Чистка / уборка', 'Чистка / уборка'), ('Перемещение (грузчик)', 'Перемещение (грузчик)'), ('Мебель (ремонт/сборка)', 'Мебель (ремонт/сборка)'), ('Садоводство', 'Садоводство'), ('Малогабаритные грузы', 'Малогабаритные грузы'), ('Крупногабаритные грузы', 'Крупногабаритные грузы'), ('Автокран', 'Автокран'), ('Экскаватор', 'Экскаватор'), ('Эвакуатор', 'Эвакуатор'), ('Землерой', 'Землерой'), ('Укладка кирпича', 'ИнтеУкладка кирпичарнет'), ('Косметика', 'Косметика'), ('Штукатурка', 'Штукатурка'), ('Моляр', 'Моляр'), ('Крыша', 'Крыша')], default='Boshqa Kasb', max_length=200, null=True),
        ),
    ]
