# Generated by Django 3.1.6 on 2021-03-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210326_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='workerArrived',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('NotAccepted', 'NotAccepted')], default='NotAccepted', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='workerGone',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('NotAccepted', 'NotAccepted')], default='NotAccepted', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='workerSelected',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('NotAccepted', 'NotAccepted')], default='NotAccepted', max_length=200, null=True),
        ),
    ]
